<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $guarded = [];

    protected $touches = ['project'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($task) {
            $task->project->recordActivity('created_task');

            // Activity::create([
            //     'project_id' => $task->project->id,
            //     'description' => 'created_task'
            // ]); Moved to the project model App\Project.php
        });

        static::updated(function ($task) {
            if (! $task->completed) return;

            $task->project->recordActivity('completed_task');

            // Activity::create([
            //     'project_id' => $task->project->id,
            //     'description' => 'completed_task'
            // ]); Moved to the project model App\Project.php
        });
    }

    public function project()
    {
        return $this->belongsTo(Project::class);
    }

    public function path()
    {
        return "/projects/{$this->project->id}/tasks/{$this->id}";
    }
}
